### ISSUE TITLE
access to https://github.com/xpring-eng/hermes-ilp/

### ISSUE THREAD

**Issue by LoisRP** [xpring-eng/Xpring-SDK-Demo#11]
In CONTRIBUTING.md, the submodule update references this repository, but although other repositories do not have an issue, this causes an authentication issue. When I enter the URL directly, I don't have access. So I think this one may be causing an error. 
https://github.com/xpring-eng/hermes-ilp/

**Comment by keefertaylor** [comment]
Did you mean to file this in Xpring-JS? 

I poked the ILP folks. You shouldn't need to clone this to get SDK demos working.

**Comment by LoisRP** [comment]
I have access now.
